In [19]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([  2, -36,  41, -53,  23,  21])

In [3]:
tensor = torch.tensor([[0.1, 0.2], [0.2, 0.3], [0.3, 0.4]])
tensor

C:\Users\Yash\AppData\Local\Temp\ipykernel_5096\3274319439.py:1: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  tensor = torch.tensor([[0.1, 0.2], [0.2, 0.3], [0.3, 0.4]])


tensor([[0.1000, 0.2000],
        [0.2000, 0.3000],
        [0.3000, 0.4000]])

In [4]:
zeros = torch.zeros(2, 2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [6]:
ones = torch.ones(3, 2)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
arange = torch.arange(10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
linspace = torch.linspace(3, 9, steps=6)
linspace

tensor([3.0000, 4.2000, 5.4000, 6.6000, 7.8000, 9.0000])

In [13]:
logspace = torch.logspace(-10, 10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

## torch.stack, torch.multinomial, torch.tril, torch.triu, input.T, torch.cat, nn.Linear, F.softmax Functions

In [17]:
# Multinomial
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
tensor = torch.tensor([1, 2, 3, 4])
out = tensor.cat((tensor, torch.tensor([5])), dim=0)
out

AttributeError: 'Tensor' object has no attribute 'cat'

In [22]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [25]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [26]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [27]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [28]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack tensors along new dimenstion
out = tensor.stack([tensor1, tensor2, tensor3])
out

AttributeError: 'Tensor' object has no attribute 'stack'

In [31]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([12.7344, -0.0692,  3.6728], grad_fn=<SqueezeBackward4>)


In [33]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax = F.softmax(tensor1, dim=0)
softmax

tensor([0.0900, 0.2447, 0.6652])

## Vector Embedding

In [34]:
# Define vocabulary size and embedding dimension
vocab_size = 10  # Let's assume we have 10 unique tokens
embedding_dim = 3  # Each token will be represented by a 3-dimensional vector

# Initialize embedding layer
embedding_layer = nn.Embedding(vocab_size, embedding_dim)

# Example input indices
input_indices = torch.tensor([1, 3, 5, 2])

# Get embeddings for the input indices
embedded = embedding_layer(input_indices)

print("Embeddings for input indices:")
print(embedded)


Embeddings for input indices:
tensor([[-0.3569, -1.3187,  0.7659],
        [-1.0549,  2.1899, -1.6070],
        [ 2.5996, -1.2191, -0.3963],
        [-0.4643, -1.8227, -1.4340]], grad_fn=<EmbeddingBackward0>)


In [37]:
tensor1 = torch.tensor([[1,2], [3,4], [5, 6]])
tensor2 = torch.tensor([[7,8,9], [10, 11, 12]])

#tensor3 = tensor1 @ tensor2
print(torch.matmul(tensor1, tensor2))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
